export const AUTHOR_RECOMMEND_REQ = "AUTHOR_RECOMMEND_REQ";
export const AUTHOR_RECOMMEND_SUCCESS = "AUTHOR_RECOMMEND_SUCCESS";
export const AUTHOR_RECOMMEND_FAIL = "AUTHOR_RECOMMEND_FAIL";
export const AUTHOR_GET_FOLLOW_REQ = "AUTHOR_GET_FOLLOW_REQ";
export const AUTHOR_GET_FOLLOW_SUCCESS = "AUTHOR_GET_FOLLOW_SUCCESS";
export const AUTHOR_GET_FOLLOW_FAIL = "AUTHOR_GET_FOLLOW_FAIL";
