export const RESET_USER_ERROR = "RESET_USER_ERROR";
export const RESET_PROFILE_MESSAGE = "RESET_PROFILE_MESSAGE";
export const RESET_STORY_ERROR = "RESET_STORY_ERROR";
export const RESET_POST_MESSAGE = "RESET_POST_MESSAGE";
export const RESET_EACH_TOPIC_STORIES = "RESET_EACH_TOPIC_STORIES";
