export const TOPIC_GET_RECOMMEND_REQ = "TOPIC_GET_RECOMMEND_REQ";
export const TOPIC_GET_RECOMMEND_SUCCESS = "TOPIC_GET_RECOMMEND_SUCCESS";
export const TOPIC_GET_RECOMMEND_FAIL = "TOPIC_GET_RECOMMEND_FAIL";
export const TOPIC_POST_FOLLOW_SUCCESS = "TOPIC_POST_FOLLOW_SUCCESS";
export const TOPIC_ERROR_FOLLOW = "TOPIC_ERROR_FOLLOW";
