export const USER_SIGN_UP_REQ = "USER_SIGN_UP_REQ";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FAIL = "USER_SIGN_UP_FAIL";
export const USER_SIGN_IN_REQ = "USER_SIGN_IN_REQ";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";
export const USER_SIGN_IN_FAIL = "USER_SIGN_IN_FAIL";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const USER_PROFILE_REQ = "USER_PROFILE_REQ,";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS,";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL,";
export const USER_PROFILE_CHANGE_REQ = "USER_PROFILE_CHANGE_REQ";
export const USER_PROFILE_CHANGE_SUCCESS = "USER_PROFILE_CHANGE_SUCCESS";
export const USER_PROFILE_CHANGE_FAIL = "USER_PROFILE_CHANGE_FAIL";
export const USER_USERNAME_BIO_CHANGE_REQ = "USER_USERNAME_BIO_CHANGE_REQ";
export const USER_USERNAME_BIO_CHANGE_SUCCESS =
  "USER_USERNAME_BIO_CHANGE_SUCCESS";
export const USER_USERNAME_BIO_CHANGE_FAIL = "USER_USERNAME_BIO_CHANGE_FAIL";
export const USER_PASSWORD_CHANGE_REQ = "USER_PASSWORD_CHANGE_REQ";
export const USER_PASSWORD_CHANGE_SUCCESS = "USER_PASSWORD_CHANGE_SUCCESS";
export const USER_PASSWORD_CHANGE_FAIL = "USER_PASSWORD_CHANGE_FAIL";
export const USER_GET_CURRENTUSER_REQ = "USER_GET_CURRENTUSER_REQ";
export const USER_GET_CURRENTUSER_SUCCESS = "USER_GET_CURRENTUSER_SUCCESS";
export const USER_GET_CURRENTUSER_FAIL = "USER_GET_CURRENTUSER_FAIL";
export const USER_GET_FOLLOWERS_FOLLOWING_REQ =
  "USER_GET_FOLLOWERS_FOLLOWING_REQ";
export const USER_GET_FOLLOWERS_FOLLOWING_SUCCESS =
  "USER_GET_FOLLOWERS_FOLLOWING_SUCCESS";
export const USER_GET_FOLLOWERS_FOLLOWING_FAIL =
  "USER_GET_FOLLOWERS_FOLLOWING_FAIL";
export const USER_REQ_PASSWORD_RESET_REQ = " USER_REQ_PASSWORD_RESET_REQ";
export const USER_REQ_PASSWORD_RESET_SUCCESS =
  "USER_REQ_PASSWORD_RESET_SUCCESS";
export const USER_REQ_PASSWORD_RESET_FAIL = "USER_REQ_PASSWORD_RESET_FAIL";
export const USER_RESET_PASSWORD_REQ = "USER_RESET_PASSWORD_REQ";
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL";
